repositories:
  - name: mm-platform-sre-prod-public
    url: europe-docker.pkg.dev/mm-platform-sre-prod/helm-charts-public
    oci: true

releases:
  - name: metabase-kaos
    namespace: kaos-prod
    chart: mm-platform-sre-prod-public/metabase/metabase
    version: 0.13.2
    values:
    - metabase-values.yaml
