apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database-pv.yaml
  - database-pvc.yaml
  - database-deployment.yaml
  - database-service.yaml
  - n8n-pv.yaml
  - n8n-pvc.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
