apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
    core.kaos.io/type: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
          volumeMounts:
            - name: n8n-app-storage
              mountPath: /home/node/.n8n
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_HOST
              value: "postgres"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n"
            - name: DB_POSTGRESDB_USER
              value: "n8n"
            - name: DB_POSTGRESDB_PASSWORD
              value: "n8n"
            - name: WEBHOOK_URL
              value: "https://83.32.50.24:8084/"
            - name: N8N_HOST
              value: "83.32.50.24"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_SSL_KEY
              value: "/home/node/certs/tls.key"
            - name: N8N_SSL_CERT
              value: "/home/node/certs/tls.crt"
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_PERSONALIZATION_ENABLED
              value: "false"
            # Optimizaciones "Pro" (Gratis)
            - name: N8N_DEFAULT_BINARY_DATA_MODE
              value: "filesystem"
            - name: EXECUTIONS_DATA_PRUNE
              value: "true"
            - name: EXECUTIONS_DATA_MAX_AGE
              value: "336"
            - name: N8N_PAYLOAD_SIZE_MAX
              value: "64"
          volumeMounts:
            - name: n8n-app-storage
              mountPath: /home/node/.n8n
            - name: n8n-certs
              mountPath: /home/node/certs
              readOnly: true
      volumes:
        - name: n8n-app-storage
          persistentVolumeClaim:
            claimName: n8n-app-pvc
        - name: n8n-certs
          secret:
            secretName: n8n-cert
