apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: runners

resources:
  - github-actions-k8s.yml
  - scheduler.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: manager-script
    files:
      - manager.sh

secretGenerator:
  - name: github-secrets
    literals:
      - GITHUB_APP_ID="1972621"
      - GITHUB_INSTALLATION_ID="103064135"
      - GITHUB_SCOPE_ORG="Ka0s-Klaus"
      - GITHUB_SCOPE="Ka0s" # Â¡Recuerda cambiar esto!
    files:
      - private-key.pem