apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - promtail-rbac.yaml
  - grafana-datasource-configmap.yaml
  - loki-configmap.yaml
  - prometheus-configmap.yaml
  - promtail-configmap.yaml
  - grafana-loki-datasource.yaml
  - grafana-service.yaml
  - loki-service.yaml
  - node-exporter-service.yaml
  - prometheus-service.yaml
  - loki-statefulset.yaml
  - cadvisor-daemonset.yaml
  - node-exporter-daemonset.yaml
  - promtail-daemonset.yaml
  - grafana-deployment.yaml
  - prometheus-deployment.yaml