apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planka
  namespace: planka
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/sub-filter: "http://192.168.1.244 https://planka.ka0s.io"
    nginx.ingress.kubernetes.io/sub-filter-once: "false"
    nginx.ingress.kubernetes.io/sub-filter-types: "*"
spec:
  ingressClassName: nginx
  rules:
    - host: planka.ka0s.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planka
                port:
                  number: 80
