apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planka-ingress
  namespace: planka
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - planka.ka0s.io
      secretName: ka0s-wildcard-tls
  rules:
    - host: planka.ka0s.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planka
                port:
                  number: 80

