apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - planka-secret.yaml
  - postgres-storage.yaml
  - postgres-deployment.yaml
  - planka-storage.yaml
  - planka-deployment.yaml
  - resource-quota.yaml
  - ingress.yaml
# Trigger deployment
