repositories:
  - name: mm-platform-sre-prod
    url: europe-docker.pkg.dev/mm-platform-sre-prod/helm-charts-public
    oci: true

releases:
  - name: grafana-kaos
    namespace: kaos-prod
    chart: mm-platform-sre-prod/grafana/grafana
    version: "10.1.3"
    values:
    - values-grafana.yaml