apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itop-ingress
  namespace: itop
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - itsm.ka0s.io
      secretName: ka0s-wildcard-tls
  rules:
    - host: itsm.ka0s.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: itop
                port:
                  number: 80
