apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itop-ingress
  namespace: itop
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: itsm.ka0s.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: itop
                port:
                  number: 80
