apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itop-ingress
  namespace: itop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
  - hosts:
    - itsm.ka0s.io
    secretName: itop-tls-secret
  rules:
  - host: itsm.ka0s.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: itop
            port:
              number: 80
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: itop
            port:
              number: 80
