apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database-pv.yaml
  - database-pvc.yaml
  - database-deployment.yaml
  - database-service.yaml
  - itop-pv.yaml
  - itop-pvc.yaml
  - itop-deployment.yaml
  - itop-service.yaml