nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazuh-indexer
      ip: 127.0.0.1
      dns:
        - wazuh-indexer
        - wazuh-indexer.soc.svc
        - wazuh-indexer.soc.svc.cluster.local

  # Wazuh server nodes
  server:
    - name: wazuh-manager
      ip: 127.0.0.1
      dns:
        - wazuh-manager
        - wazuh-manager.soc.svc
        - wazuh-manager.soc.svc.cluster.local

  # Wazuh dashboard nodes
  dashboard:
    - name: wazuh-dashboard
      ip: 127.0.0.1
      dns:
        - wazuh-dashboard
        - wazuh-dashboard.soc.svc
        - wazuh-dashboard.soc.svc.cluster.local
        - soc.ka0s.io
