apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-indexer-config
  namespace: wazuh
data:
  opensearch.yml: |
    cluster.name: wazuh-cluster
    node.name: wazuh-indexer-0
    discovery.type: single-node
    network.host: 0.0.0.0
    plugins.security.ssl.http.enabled: true
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.authcz.admin_dn:
      - CN=admin