repositories:
  - name: mm-platform-sre-prod
    url: europe-docker.pkg.dev/mm-platform-sre-prod/helm-charts-public
    oci: true

releases:
  - name: postgresql-kaos
    namespace: kaos-prod
    chart: mm-platform-sre-prod/bitnami/postgresql
    version: 16.2.1
    values:
    - values-postgresql.yaml