apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongo

resources:
  - namespace.yaml
  - mongo-secret.yaml
  - mongo-storage.yaml
  - mongo-statefulset.yaml
  - mongo-service.yaml