resources:
  - namespace.yaml
  - role-jenkins.yaml
  - role.yaml
  - rolebinding-jenkins.yaml
  - rolebinding.yaml
  - secret-sa-token-jenkins.yaml
  - serviceaccount-jenkins.yaml
  - serviceaccount.yaml
  - rolebinding-gke.yaml