#ENC[AES256_GCM,data:hxwhUUYCVK6KP9rwehLCSpBWicF2s48mdP2i3glLVZR2biDD8TbhrXRKea2lKau37FJWog==,iv:5ePdUIq7at+0ondYJtj8xHQNtXY4ewJK9fMvgiRyeb0=,tag:H4h/+c4H8qYMTRMIKvkFNw==,type:comment]
alertmanager:
    config:
        opsgenie:
            api_key: ""
sops:
    gcp_kms:
        - resource_id: projects/mm-cloudbuild/locations/europe/keyRings/squads_secrets/cryptoKeys/platform-sre_crypto_key
          created_at: "2025-10-08T11:47:08Z"
          enc: CiUAOIhAxyUmx9kiCMVKP9uvlHSjtXBlNJ+3dtDFNBM1dFS4KEFPEkkA3onv81A+nZqZxwTndlp5fcr3U3GHd46fLYrwcEuC1EpEAxromYuGMB8DD5C5AfJ9ivq4RNSTZzxfAMqqpiJdpg1Q6x7jFnT7
    lastmodified: "2025-10-08T11:47:08Z"
    mac: ENC[AES256_GCM,data:sWnnrFMB1yVry85em22TQvI1eOSqo5NjpO843FnuDCD4rYJJEnueZxaOXrUkV2kHfZ+NCtJ8ECUns7hjX5mThFQGB+k9bMopeon3NXXWSf4XNOd6uz7aSXlDI+KAFXS6ptJkm3VGoF5vJJT7vH58uYVWSyYYTMBnkZfUThNEB70=,iv:1TPQuewmRUHot1uoodl9nMU7kSZFd9Qmidw/2K8XGAQ=,tag:KBdrxFcpX78b+uegXsG54A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2