repositories:
  - name: mm-platform-sre-prod
    url: europe-docker.pkg.dev/mm-platform-sre-prod/helm-charts-public
    oci: true

releases:
  - name: mongodb-kaos
    namespace: kaos-prod
    chart: mm-platform-sre-prod/bitnami/mongodb
    version: 16.5.45
    values:
    - values-mongodb.yaml
