hosts:
  - multicloudtrack-grafana.masorange.es

app:
  name: grafana
  port: 3000
  labelSelector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-kaos
  healthCheck:
    path: /app-health/grafana/readyz
    port: 15020

armor:
  securityPolicy: ""

iap:
  enabled: true

gateway:
  name: public-http
  namespace: gateways

gcpBackend:
  logging:
    enabled: false