apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - elasticsearch-service.yaml
  - elasticsearch-statefulset.yaml
  - kibana-deployment.yaml
  - kibana-service.yaml
  - logstash-configmap.yaml
  - logstash-deployment.yaml
  - logstash-service.yaml