apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elastic
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
  pipeline.conf: |
    input {
      mongodb {
        uri => 'mongodb://root:$(MONGO_ROOT_PASSWORD)@mongo.mongo.svc.cluster.local:27017/kaosdb?authSource=admin'
        placeholder_db_dir => '/usr/share/logstash/data/pldb'
        collection => 'kaos'
        batch_size => 50
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "kaos-%{+YYYY.MM.dd}"
      }
    }